[chrome]
host = "localhost"
port = 9222

[consul]
address = "localhost:8500"
scheme = "http"
datacenter = "datacenter1"
action = "foo/action"
newurl = "foo/url"
runningurl = "foo/current"

[delay]
interval = 1000
